### ISSUE TITLE
[FEATURE] Add Yapf as pre-commit hook

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#106]
We should have a script to pre-format the code before sending a pull request:
https://github.com/google/yapf/tree/master/plugins

**Comment by edgarriba** [comment]
@ducha-aiki what do you think about it ? We currently use autopep8, however I recently discovered `black` to autoformat.

**Comment by ducha-aiki** [comment]
I am mostly doing this manually, because autopep8 and black are ugly. 
So I am against pre-hook

**Comment by edgarriba** [comment]
closing this. If anyone have any objection, please feel free to reopen the discussion.
