### ISSUE TITLE
[FEAT] Switch torch asserts

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#107]
We currently have custom assertion to check equal torch tensors
```python
import utils # test utilities
assert utils.check_equal_torch(trans_02_hat, trans_02)
```

this can be replaced by:
```python
from torch.testing import  assert_allclose
assert_allclose(rans_02_hat, trans_02)
```

**Comment by rsdel2007** [comment]
Do we have to replace from all the places where it is used?

**Comment by edgarriba** [comment]
closing this since in the last commits this has been incrementally fixed
