### ISSUE TITLE
[FEAT] Batch support for image_to_tensor/tensor_to_image

### ISSUE THREAD

**Issue by jiangwei221** [arraiyopensource/kornia#144]
Current implemetation only works for (C, H, W) ->(H, W, C), maybe is good to have (B, C, H, W) ->(B, H, W, C).
Also, if we define this function works on image, should we limit the number of channels to only 1 and 3? seem other number of channels do not make sense, at least cannot be plot via matplotlib...

**Comment by edgarriba** [comment]
hi @jiangwei221 thanks for your interest in the library, we can definitely support batched version. It can be easily implemented by changing the permute indices.

For [image_to_tensor](https://github.com/arraiyopensource/kornia/blob/master/kornia/utils/image.py#L29) can be done by doing something like this:
```python
return x.transpose(-3, -2).transpose(-2, -1)
```
I guess will be be similar for tensor_to_image. I'm not quite if we should restrict to 1 or 3 channels, what if rgbd or multispectral images ? the target here is to extend traditional stuff to work on high dimensional tensors :D

**Comment by edgarriba** [comment]
closing in favor of https://github.com/arraiyopensource/kornia/pull/150
