### ISSUE TITLE
function 'convert_points_from_homogeneous' may not work

### ISSUE THREAD

**Issue by tang-peng** [arraiyopensource/kornia#146]
This package is a great job. 

However, in the function `convert_points_from_homogeneous`, I found:

```
# we check for points at infinity
    z_vec: torch.Tensor = points[..., -1:]
    scale: torch.Tensor = torch.tensor(1.) / torch.clamp(z_vec, EPS)

    return scale * points[..., :-1]
```

This code does not work if the `z_vec` is negative, because its value is restricted by EPS. However, the last element of the homogeneous coordinate vector can be negative. 

So, is that a bug?

**Comment by edgarriba** [comment]
@tang-peng thanks for pointing this out. It's already a known issue, check: https://github.com/arraiyopensource/kornia/issues/116

the solution could be something like:
```python
scale: torch.Tensor = torch.where(torch.abs(z_vec) > EPS,
    torch.tensor(1.) / z_vec,  torch.ones_like(z_vec))
```

please, feel free to open a PR to fix it.

**Comment by bhack** [comment]
Check https://github.com/arraiyopensource/kornia/pull/148

**Comment by bhack** [comment]
Can we close now?
