### ISSUE TITLE
Contributor covenant

### ISSUE THREAD

**Issue by bhack** [arraiyopensource/kornia#149]
Can we adopt [contributor covenant](https://www.contributor-covenant.org/)?

**Comment by edgarriba** [comment]
absolutely

**Comment by edgarriba** [comment]
see https://github.com/ContributorCovenant/contributor_covenant/pull/675

**Comment by bhack** [comment]
You can add  [![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v1.4%20adopted-ff69b4.svg)](code-of-conduct.md)  in the readme.me

**Comment by edgarriba** [comment]
mmm, too many badges. Want to keep it simple :D
I will add a small section with a couple of lines in the readme pointing this out.

**Comment by edgarriba** [comment]
closing this due to https://github.com/arraiyopensource/kornia/pull/151 and https://github.com/ContributorCovenant/contributor_covenant/pull/675
