### ISSUE TITLE
Quaternion Representation

### ISSUE THREAD

**Issue by varunagrawal** [arraiyopensource/kornia#178]
Currently, all the quaternion operations assume the structure is `[x, y, z, w]`. However, as per the vision/robotics/graphics literature as well as countless libraries like [transforms3d](https://matthew-brett.github.io/transforms3d/reference/transforms3d.quaternions.html) and [pyquaternion](http://kieranwynn.github.io/pyquaternion/#default), the canonical representation for quaternions is always `[w, x, y, z]`.

From looking at the source code, it seems that the tensorflow convention has been adopted and this is highly non-standard, as well as the fact that the documentation doesn't mention this.

I propose switching to the standard `[w, x, y, z]` representation which is ubiquitous. I can submit a PR for this.

**Comment by edgarriba** [comment]
@varunagrawal Sure, go ahead with it. At some point I was even planning to implement a Quaternion class. We are open to discuss it.

**Comment by bhack** [comment]
What is the standard in very popular 3d engines?
https://docs.unity3d.com/ScriptReference/Quaternion.html

https://api.unrealengine.com/INT/API/Runtime/Core/Math/FQuat/index.html

**Comment by varunagrawal** [comment]
@bhack that's interesting. Even ROS uses `[x, y, z, w]` so there doesn't seem to be a standard. Would it then be easier to simply update the docs and let users know that they should expect quaternions in `[x, y, z, w]`?

**Comment by varunagrawal** [comment]
Closing this since #179 fixes it.
