### ISSUE TITLE
Make test not stop on 1st failure

### ISSUE THREAD

**Issue by ducha-aiki** [arraiyopensource/kornia#188]
When I do "make test" it goes just up to first failure and then stops. It would be much better, if instead it goes for all the tests always.

> test/geometry/test_conversions.py::TestQuaternionLogToExp::test_jit FAILED                                                                                                                                                                        [ 37%]
> 
> ======================================================================================================================= FAILURES ========================================================================================================================
> ____________________________________________________________________________________________________________ TestQuaternionLogToExp.test_jit ____________________________________________________________________________________________________________
> 
> self = <test.geometry.test_conversions.TestQuaternionLogToExp object at 0x7f0410042b38>
> 
>     def test_jit(self):
>         op = kornia.quaternion_log_to_exp
> >       op_script = torch.jit.script(op)
> 
> test/geometry/test_conversions.py:223: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /home.dokt/mishkdmy/anaconda3/envs/fastai1/lib/python3.7/site-packages/torch/jit/__init__.py:823: in script
>     ast = get_jit_def(obj)
> /home.dokt/mishkdmy/anaconda3/envs/fastai1/lib/python3.7/site-packages/torch/jit/frontend.py:158: in get_jit_def
>     return build_def(ctx, py_ast.body[0], type_line, self_name)
> /home.dokt/mishkdmy/anaconda3/envs/fastai1/lib/python3.7/site-packages/torch/jit/frontend.py:198: in build_def
>     build_stmts(ctx, body))
> /home.dokt/mishkdmy/anaconda3/envs/fastai1/lib/python3.7/site-packages/torch/jit/frontend.py:122: in build_stmts
>     stmts = [build_stmt(ctx, s) for s in stmts]
> /home.dokt/mishkdmy/anaconda3/envs/fastai1/lib/python3.7/site-packages/torch/jit/frontend.py:122: in <listcomp>
>     stmts = [build_stmt(ctx, s) for s in stmts]
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <torch.jit.frontend.StmtBuilder object at 0x7f04112bd438>, ctx = <torch.jit.frontend.SourceContext object at 0x7f03f5fc3c50>, node = <_ast.AnnAssign object at 0x7f03f5fd48d0>
> 
>     def __call__(self, ctx, node):
>         method = getattr(self, 'build_' + node.__class__.__name__, None)
>         if method is None:
> >           raise UnsupportedNodeError(ctx, node)
> E           torch.jit.frontend.UnsupportedNodeError: annotated assignments aren't supported
> E               if not isinstance(quaternion, torch.Tensor):
> E                   raise TypeError("Input type is not a torch.Tensor. Got {}".format(
> E                       type(quaternion)))
> E           
> E               if not quaternion.shape[-1] == 3:
> E                   raise ValueError(
> E                       "Input must be a tensor of shape (*, 3). Got {}".format(
> E                           quaternion.shape))
> E               # compute quaternion norm
> E               norm_q: torch.Tensor = torch.norm(
> E               ~ <--- HERE
> E                   quaternion, p=2, dim=-1, keepdim=True).clamp(min=eps)
> E           
> E               # compute scalar and vector
> E               quaternion_vector: torch.Tensor = quaternion * torch.sin(norm_q) / norm_q
> E               quaternion_scalar: torch.Tensor = torch.cos(norm_q)
> E           
> E               # compose quaternion and return
> E               quaternion_exp: torch.Tensor = torch.cat(
> E                   [quaternion_vector, quaternion_scalar], dim=-1)
> 
> /home.dokt/mishkdmy/anaconda3/envs/fastai1/lib/python3.7/site-packages/torch/jit/frontend.py:173: UnsupportedNodeError
> =================================================================================================== 1 failed, 153 passed, 3 skipped in 17.97 seconds ====================================================================================================
> Makefile:6: recipe for target 'test-cpu' failed
> make: *** [test-cpu] Error 1
> (fastai1) mishkdmy@woska:~/dev/kornia$ vim test/geometry/test_conversions.py
>

**Comment by edgarriba** [comment]
I'm looking for any pytest command line option to do so

**Comment by edgarriba** [comment]
@ducha-aiki is this still happening ?
