### ISSUE TITLE
[FEATURE] Add padding_mode option to transformations

### ISSUE THREAD

**Issue by darleybarreto** [arraiyopensource/kornia#205]
I would like to point out some small changes on functions and classes using HomographyWarper. For example, when performing any transformation (Rotate, Translate, etc), it is not possible to change the default padding_mode, although HomographyWarper class has a field for this.

**Comment by edgarriba** [comment]
@darleybarreto thanks for pointing out. I add this feature as a request so that we can include it in the next release. As usual, any help will be appreciated :D

**Comment by edgarriba** [comment]
closing this for duplication https://github.com/arraiyopensource/kornia/issues/218
