### ISSUE TITLE
kornia.readthedocs.io is not pointing to this repository!

### ISSUE THREAD

**Issue by jasam-sheja** [arraiyopensource/kornia#217]
Hello, 
This might not be the place for such issues, but I don't where else to put it.

The links on this repository are leading to kornia.readthedocs.io. However, The 'Edit on GitHub' at kornia.readthedocs.io is not leading to this repository but actually gives a 404 page on GitHub.

**Comment by edgarriba** [comment]
hi @jasam-sheja this should fix it: https://github.com/arraiyopensource/kornia/commit/5a153430806ad51be0caefa5969974ebb8840a93
