### ISSUE TITLE
How could I set affine transform fill value?

### ISSUE THREAD

**Issue by CoinCheung** [arraiyopensource/kornia#220]
Hi, 

Thanks for providing this helpful library, I have just read the api documentation, and I did not find the option to set the fill value for affine transformations. How could I do this please?

**Comment by edgarriba** [comment]
@CoinCheung not sure if I understand what are you asking for.  Could you provide a more explicit example or any snippet so that can be easily implemented in case it is not. In that case, I'll add as a feature request.

**Comment by ducha-aiki** [comment]
@CoinCheung do you mean border-fill mode?

**Comment by CoinCheung** [comment]
yes, suppose I use affine transform to shear an image, after the operation, there would be triangle borders at the corners of the image. Opencv set these corners to be 0 by default, but it also leaves an option to set it to other values: `cv2.warpAffine(..., borderValue=255)`. Could I do the same thing with kornia ?

**Comment by edgarriba** [comment]
oh, I see. I think this is related https://github.com/arraiyopensource/kornia/issues/218

**Comment by edgarriba** [comment]
closing for duplication in #218
