### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by bhack** [arraiyopensource/kornia#23]
It could be interesting to evaluate benchmark against optimized impl. like https://docs.nvidia.com/cuda/npp/group__nppi.html

**Comment by edgarriba** [comment]
@bhack could be interesting also to see effect of the PyTorch JIT compiler. I've seen also that Pyro adopted the possibility to run in eager/script modes through JIT.
https://github.com/uber/pyro/releases
http://pyro.ai/examples/jit.html

**Comment by edgarriba** [comment]
@bhack we provide some benchmarks in the paper. I close this by now. We can think to have a tutorial showing performance.
