### ISSUE TITLE
No module named test.common error

### ISSUE THREAD

**Issue by HassanAlsamahi** [arraiyopensource/kornia#241]
I am trying to test the colors conversion using the script 
`test_gray.py` running from every directory, `kornia`, `kornia/test`, and `kornia/test/colors`, the same error pops. what to do to run tests?

the error:
`Traceback (most recent call last):
  File "test/test_losses.py", line 5, in <module>
    from test.common import device_type
ModuleNotFoundError: No module named 'test.common'`

**Comment by edgarriba** [comment]
You should run tests with `pytest test_`

**Comment by HassanAlsamahi** [comment]
thanks that worked
