### ISSUE TITLE
How to use kornia.utils.metrics.mean_iou?

### ISSUE THREAD

**Issue by anhle-uet** [arraiyopensource/kornia#245]
I want to compute mIOU for evaluating semantic segmentation results. Does **input** and **target** have to be converted to one-hot by: **kornia.utils.one_hot** or just stay the same with shape **NxHxW**?

**Comment by ducha-aiki** [comment]
They don`t need to be one-hot, instead integers ( classes idxs). I recommend to convert BxChxHxW to (B*H*W)xCh

tensor.permute(0, 2, 3, 1).view(-1, ch)
