### ISSUE TITLE
[Feature Request] fp16 support?

### ISSUE THREAD

**Issue by turboxin** [arraiyopensource/kornia#275]
Hi, does kornia support fp16 now?

**Comment by edgarriba** [comment]
@turboxin we don't have half precision tests so expect adventures with it. Do you have any immediate need ? we could start trying those.

**Comment by turboxin** [comment]
Hi @edgarriba, thanks for replying.
I tested warp_affine with fp16 input, it seems that torch.inverse() used in line49 of kornia.geometry.transform.imgwarp.py doesn't support fp16 with this error: "inverse_cuda" not implemented for "Half".
I don't have immediate need now since I could just convert fp16 input to fp32 before putting into warp_affine and convert back afterwards. But I guess it would be great if kornia suppport half precision since it seems to be a trend.

**Comment by bhack** [comment]
Partially this depend on the base op converge on FP16 in pytorch directly.
