### ISSUE TITLE
[JIT] Unit test for torch script

### ISSUE THREAD

**Issue by Wizaron** [arraiyopensource/kornia#38]
If we decouple the pytest functions into two parts, one for functionality to test and the other one for testing as in the following example, we can carry out tests for both pytorch and torch script in a single test function.

If it is OK, I am going to decouple them prior to writing tests for torch script.

Do you have any suggestions?

```python
def rad2deg(x_rad):
    # convert radians/degrees
    x_deg = tgm.rad2deg(x_rad)
    x_deg_to_rad = tgm.deg2rad(x_deg)

    return x_deg, x_deg_to_rad


@pytest.mark.parametrize("device_type", TEST_DEVICES)
@pytest.mark.parametrize("batch_shape", [
    (2, 3), (1, 2, 3), (2, 3, 3), (5, 5, 3), ])
def test_rad2deg(batch_shape, device_type):
    # trace
    dummy_input = torch.rand(batch_shape)
    rad2deg_traced = torch.jit.trace(rad2deg, dummy_input)

    # generate input data
    x_rad = tgm.pi * torch.rand(batch_shape)
    x_rad = x_rad.to(torch.device(device_type))

    # convert radians/degrees
    x_deg, x_deg_to_rad = rad2deg(x_rad)
    x_deg_traced, x_deg_to_rad_traced = rad2deg_traced(x_rad)

    # compute error
    error = utils.compute_mse(x_rad, x_deg_to_rad)
    assert pytest.approx(error.item(), 0.0)

    error_traced = utils.compute_mse(x_rad, x_deg_to_rad_traced)
    assert pytest.approx(error_traced.item(), 0.0)

    # functional
    assert torch.allclose(x_deg, tgm.RadToDeg()(x_rad))
    assert torch.allclose(x_deg_traced, tgm.RadToDeg()(x_rad))

    # evaluate function gradient
    assert gradcheck(tgm.rad2deg, (utils.tensor_to_gradcheck_var(x_rad),),
                     raise_exception=True)
```

**Comment by edgarriba** [comment]
@Wizaron cool that you want to go ahead with this ! there's one thing that I'm not quite sure yet - I see to many assertions, and usually that's an anti-pattern for test design :D

I would go for something more modular by provding proper test classes to cover the different needs. 

Maybe @carlosb1 could give us an intuition to proceed with this since he's working on the `mypy` test integration.

**Comment by carlosb1** [comment]
A few thing. First, It is added an assert for "case" to test, for this reason it should be a bad design has multiple asserts in a test.. it is better split for every case. Also, it would be good to split tests that they are testing feature / functionality or if it is checking the function (unitary test). For this last case, we can split them in different files, and when the set of number of tests increase too much, It would be move directly to different folders. One idea could be move tests in three main types: stress or system tests (to check performance), functional tests (to check functionality and to analyse if the functions are working well) and finally unitary tests (to check outputs for each function).

**Comment by edgarriba** [comment]
@Wizaron could you investigate this ? https://github.com/arraiyopensource/torchgeometry/issues/45
@carlosb1 could you share the snippet for testing you mention ?

**Comment by edgarriba** [comment]
@Wizaron @carlosb1 In my last two PR I've been adopting this pattern for test. Let me know your thoughts about how you can adapt it to JIT and others.

**Comment by carlosb1** [comment]
@edgarriba @Wizaron . From my side, it seems enough, I was checking different options for splitting the test and I couldn't find anything better.

**Comment by edgarriba** [comment]
unit tests with JIT are already included in latest cointributions, check: https://github.com/arraiyopensource/kornia/blob/master/test/filters/test_filters.py#L52

closing this.
