### ISSUE TITLE
[DOCS] Update data types links

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#47]
Some data types are yet not well linked. Need to check the source code and update types according to mypy if possible.

Example [link](https://github.com/arraiyopensource/torchgeometry/blob/master/torchgeometry/imgwarp.py#L74-L75)
```python
  Args:
    M (Tensor): transformation matrix. # WRONG
    M (torch.Tensor): transformation matrix. # CORRECT
```

**Comment by kajal-puri** [comment]
Hi @edgarriba 

Please review my [pull request] (https://github.com/arraiyopensource/torchgeometry/pull/97) for this issue.

**Comment by edgarriba** [comment]
closing this since is mostly covered in last commits.
