### ISSUE TITLE
[TEST] Speed up CI builds and GPU support

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#51]
Each time a pull request is sent, the current [Travis script ](https://github.com/arraiyopensource/torchgeometry/blob/master/.travis.yml) builds the environment for each of the stages.

We should be able to cache the conda packages and reuse it for all the stages.

**Comment by edgarriba** [comment]
we should start thinking a bout migrating to an alternative to give support to gpu testing:

CircleCI seems to give support to do that: 
https://circleci.com/docs/2.0/gpu/

**Comment by bhack** [comment]
I don't know if it is available on the managed version.
Can you ask in channels to the commiters of these files https://github.com/pytorch/pytorch/commits/master/.circleci?

**Comment by edgarriba** [comment]
Closing this in favor of 30099b4b0481f4151b893f77d7bf297ee47d268b
