### ISSUE TITLE
[FEAT] DepthWarper using inverse depth

### ISSUE THREAD

**Issue by edgarriba** [arraiyopensource/kornia#85]
We started the discussion in #79  whether the `DepthWarper` should warp by depth or inverse depth.

@ClementPinard @versatran01 Propose to use inverse depth for numerical stability issues.
Screenshot of one the arguments for that:
![screenshot from 2019-02-28 14-37-04](https://user-images.githubusercontent.com/5157099/53570411-b328a880-3b66-11e9-9bfb-eeb420b35f2f.png)

Currently the warper works as follows:
```python
# module
pinhole_dst = PinholeCamera(...)
pinhole_src = PinholeCamera(...)
warper = DepthWarper([pinhole_dst, ], height, width)
warper.compute_projections(pinhole_src)
img_src = warper(depth_src, img_dst)
# functional
img_src = depth_warp([pinhole_dst, ], pinhole_ref, depth_src, (height, width))
```

I was testing the API, and might be much simple to receive a single pinhole instance as destination. Notice that the internal members extrinsics and intrinsics are already batched.

Let's continue the discussion here.

**Comment by versatran01** [comment]
Currently in my implementation, eps is used only in one place, which is just like 
@ClementPinard said, to clamp the depth the eps when doing the mentioned inverse operation.

**Comment by versatran01** [comment]
![selection_001](https://user-images.githubusercontent.com/1883423/53585891-faa63900-3b54-11e9-95fa-11beb6160b8b.jpg)

This is an example of warping using vkitti ground truth pose and depth. From left to right, target image,  synthesized image and their difference.

**Comment by edgarriba** [comment]
@versatran01 nice ! would be great to adapt your codes with the current class.

**Comment by edgarriba** [comment]
Going to refactor at some point the depth warper. We can resume the discussion by the. Closing this now.
